version: 0.2
    
env:
   variables:
     PROJECT: netwebapp
     DOTNET_CORE_RUNTIME: 3.1

phases:   
  install:
    runtime-versions:
      dotnet: ${DOTNET_CORE_RUNTIME}
      
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore ./${PROJECT}/${PROJECT}.csproj
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build -c Release ./${PROJECT}/${PROJECT}.csproj

      
  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release  -r linux-x64 -o ./build_output ./${PROJECT}/${PROJECT}.csproj --self-contained false
      - cp Procfile ./build_output

artifacts:
  files:
    - '**/*'
  base-directory: ./build_output
  discard-paths: no

